[package]
name = "git-version"
version = "0.1.0"
authors = ["droundy <roundyd@physics.oregonstate.edu>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
proc-macro2 = "0.4.24"
